#ifndef CONFIG_H
#define CONFIG_H

#include <SDL2/SDL.h>

// === WINDOW SETTINGS ===
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "RageBait"
#define TARGET_WIDTH 800
#define TARGET_HEIGHT 600

// === PLAYER SETTINGS ===
#define PLAYER_SPEED 120.0f
#define PLAYER_JUMP_FORCE 500.0f
#define PLAYER_GRAVITY 300.0f
#define PLAYER_JUMP_DURATION 300.0f
#define PLAYER_JUMP_REDUCED_FORCE 350.0f
#define PLAYER_FAST_FALL_SPEED 280.0f
#define PLAYER_START_X 80.0f
#define PLAYER_START_Y 100.0f
#define PLAYER_WIDTH 32.0f
#define PLAYER_HEIGHT 48.0f

// === DASH SETTINGS ===
#define PLAYER_DASH_SPEED 450.0f
#define PLAYER_DASH_DURATION 150.0f
#define PLAYER_DASH_COOLDOWN 200.0f

// === ANIMATION SETTINGS ===
#define ANIMATION_FRAME_TIME 100.0f
#define SPRITE_SHEET_TILE_WIDTH 32
#define SPRITE_SHEET_TILE_HEIGHT 48

// === COLLISION BOUNDS SETTINGS ===
#define CROUCH_Y_OFFSET_PERCENT 0.42f
#define CROUCH_HEIGHT_REDUCTION_PERCENT 0.52f
#define CROUCH_X_OFFSET_RIGHT_PERCENT 0.25f
#define CROUCH_X_OFFSET_LEFT_PERCENT 0.0f
#define CROUCH_WIDTH_REDUCTION_PERCENT 0.25f

#define MOVING_Y_OFFSET_PERCENT 0.21f
#define MOVING_HEIGHT_REDUCTION_PERCENT 0.29f
#define MOVING_X_OFFSET_RIGHT_PERCENT 0.25f
#define MOVING_X_OFFSET_LEFT_PERCENT 0.0f
#define MOVING_WIDTH_REDUCTION_PERCENT 0.34f

#define IDLE_Y_OFFSET_PERCENT 0.21f
#define IDLE_HEIGHT_REDUCTION_PERCENT 0.29f
#define IDLE_X_OFFSET_RIGHT_PERCENT 0.31f
#define IDLE_X_OFFSET_LEFT_PERCENT 0.16f
#define IDLE_WIDTH_REDUCTION_PERCENT 0.53f

#define JUMPING_Y_OFFSET_PERCENT 0.0f
#define JUMPING_HEIGHT_REDUCTION_PERCENT 0.0f
#define JUMPING_X_OFFSET_RIGHT_PERCENT 0.375f
#define JUMPING_X_OFFSET_LEFT_PERCENT 0.375f
#define JUMPING_WIDTH_REDUCTION_PERCENT 0.66f

// === TILE SETTINGS ===
#define DEFAULT_TILE_SIZE 32
#define DEFAULT_TILE_WIDTH 32
#define DEFAULT_TILE_HEIGHT 32

// === MAP SETTINGS ===
#define DEFAULT_MAP_WIDTH 90
#define DEFAULT_MAP_HEIGHT 15
#define MAP_FILE_PATH "../resources/map.tmx"
#define BACK_GROUND "bg"
#define COINS_LAYER_NAME "coin"
#define SLOW_LAYER_NAME "slow"
#define DISAPPEAR_LAYER_NAME "timer"
#define TRAPS_LAYER_NAME "trap"
#define ARROW_LAYER_NAME "arrow"

// === RESOURCE PATHS ===
#define PLAYER_TEXTURE_PATH "../resources/monkey.png"

// === SPECIAL TILE BEHAVIOR ===
#define SLOW_SPEED_MULTIPLIER 0.5f
#define SLOW_JUMP_MULTIPLIER 0.7f
#define DISAPPEAR_DELAY_MS 1000.0f
#define REAPPEAR_DELAY_MS 3000.0f
#define TRAP_HITBOX_REDUCTION 1.0f

// === ARROW SETTINGS ===
#define ARROW_SPEED 150.0f
#define ARROW_WIDTH 16.0f
#define ARROW_HEIGHT 16.0f

// === INPUT BINDINGS ===
#define KEY_MOVE_LEFT SDL_SCANCODE_A
#define KEY_MOVE_LEFT_ALT SDL_SCANCODE_LEFT
#define KEY_MOVE_RIGHT SDL_SCANCODE_D
#define KEY_MOVE_RIGHT_ALT SDL_SCANCODE_RIGHT
#define KEY_JUMP SDL_SCANCODE_W
#define KEY_JUMP_ALT1 SDL_SCANCODE_UP
#define KEY_JUMP_ALT2 SDL_SCANCODE_SPACE
#define KEY_CROUCH SDL_SCANCODE_LCTRL
#define KEY_FAST_FALL SDL_SCANCODE_S
#define KEY_FAST_FALL_ALT SDL_SCANCODE_DOWN
#define KEY_DASH SDL_SCANCODE_LSHIFT

// === GAME SETTINGS ===
#define MAX_PLAYER_HEALTH 3
#define PERFORMANCE_FREQUENCY_DIVISOR 1000.0
#define ALPHA_OPAQUE 255
#define GROUND_CHECK_HEIGHT 2.0f

// === RENDERING SETTINGS ===
#define RENDER_SCALE_QUALITY "0" // Nearest neighbor for pixel art

// === PHYSICS SETTINGS ===
#define COLLISION_BOUNDS_PADDING 0.0f

// === PROJECTILE PHYSICS ===
#define PROJECTILE_GRAVITY 300.0f
#define COIN_BOUNCE_DAMPING 100.0f
#define COIN_BOUNCE_DURATION 500.0f // ms
#define BULLET_VEL_X 10.0f
#define BULLET_VEL_Y 10.0f
#define COINS_BOUNCING_DEFAULT true

#endif // CONFIG_H